# Generated by Django 3.1.7 on 2021-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0003_auto_20210802_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='host',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
