# Generated by Django 3.1.7 on 2021-08-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0005_auto_20210802_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='CodTournaments',
        ),
        migrations.AlterModelOptions(
            name='codtournaments',
            options={'verbose_name': 'COD Participant', 'verbose_name_plural': 'COD Participants'},
        ),
    ]
