# Generated by Django 3.1.7 on 2021-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0011_acparticipants_actournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='streamers/')),
            ],
        ),
    ]
