# Generated by Django 3.1.7 on 2021-08-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0012_streamers'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamers',
            name='descr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
