# Generated by Django 3.1.7 on 2021-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0013_streamers_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='streamers',
            name='link',
        ),
        migrations.AddField(
            model_name='streamers',
            name='FBlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='streamers',
            name='YTlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
