# Generated by Django 3.1.7 on 2021-08-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0014_auto_20210804_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamers',
            name='FBlink',
        ),
        migrations.RemoveField(
            model_name='streamers',
            name='YTlink',
        ),
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='streamers',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='FBlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='YTlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
