# Generated by Django 3.1.7 on 2021-08-04 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0018_streamers_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='actournaments',
            name='streamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='john.streamers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armatournaments',
            name='streamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='john.streamers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codtournaments',
            name='streamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='john.streamers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cstournaments',
            name='streamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='john.streamers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='f1tournaments',
            name='streamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='john.streamers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mctournaments',
            name='streamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='john.streamers'),
            preserve_default=False,
        ),
    ]
