# Generated by Django 3.1.7 on 2021-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0019_auto_20210804_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='codtournaments',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
