# Generated by Django 3.1.7 on 2021-08-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0020_codtournaments_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codtournaments',
            old_name='room',
            new_name='roomlink',
        ),
    ]
