# Generated by Django 3.1.7 on 2021-08-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0021_auto_20210804_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
