# Generated by Django 3.1.7 on 2021-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0022_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamers',
            name='ytID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
